# Generated by Django 3.2.9 on 2021-11-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56, verbose_name='title')),
                ('description', models.CharField(max_length=128, verbose_name='description')),
                ('price', models.FloatField(default=0.0, verbose_name='price')),
                ('video', models.FileField(blank=True, null=True, upload_to='', verbose_name='files/video')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
    ]
