# Generated by Django 3.2.9 on 2021-11-15 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='ordered at')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='courseapp.coursemodel')),
            ],
        ),
    ]
